## Phase-1 :  Learn about Numpy basics


In [2]:

import numpy as np

## Creating array from List


In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


##  List vs Numpy

In [5]:
py_list = [1,2,3]
print("python list multiplication",py_list *2) 


np_array = np.array([1,2,3]) # element wise multiplication
print("numpy array multiplication",np_array *2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time",time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time",time.time()-start)

python list multiplication [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]

 List operation time 0.048150062561035156

 Numpy operation time 0.0036716461181640625


# Creating array from scratch

In [6]:
import math
zeros = np.zeros((3,4))
print("Zeros array:\n",zeros)
ones = np.ones((3,4))
print("Ones array:\n",ones)

full = np.full((2,2),7)
print("Full array:\n",full)

random = np.random.random((2,3))
print("Random array:\n",(random))


seq = np.arange(0,10,2)
print("Sequence",seq)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array:
 [[7 7]
 [7 7]]
Random array:
 [[0.74281458 0.50770982 0.15617057]
 [0.64148059 0.13772897 0.04997334]]
Sequence [0 2 4 6 8]


## Vector, Matrix and Tensor


In [7]:
vector = np.array([1,2,3])
print("Vector: ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: ",matrix)

tensor = np.array([[1,2],[4,5],[7,9],[10,12],[13,15]])
print("\n tensor: ",tensor)

Vector:  [1 2 3]
matrix:  [[1 2 3]
 [4 5 6]]

 tensor:  [[ 1  2]
 [ 4  5]
 [ 7  9]
 [10 12]
 [13 15]]


## Array Properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6] ,
                [7,8,9]])   
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("Data Type",arr.dtype)

Shape (3, 3)
Dimension 2
Size 9
Data Type int64


## Array reshaping

In [21]:
arr = np.arange(12)
print("Original array", arr)
reshaped_arr = arr.reshape((3,4))
print("\n Reshaped array",reshaped_arr)
flattened_arr = reshaped_arr.flatten()
print("\n Flattened array",flattened_arr)

# ravel(returns view of original, instead of copy)
raveled = reshaped_arr.ravel()
print("Raveled array",raveled)

#Transpose 
transpose = reshaped_arr.T
print("\n Transposed array \n",transpose)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
