## Phase-2 : Operations on Numpy arrays

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slice: ",arr[2:7])

print("With Step:",arr[1:8:2])
print("Negative Indexing:",arr[-3])
      

Basic Slice:  [3 4 5 6 7]
With Step: [2 4 6 8]
Negative Indexing: 8


In [13]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element of 2D: ",arr_2d[1,2])
print("Entire Row:",arr_2d[1])
print('Entire Column:',arr_2d[:,1])

Specific element of 2D:  6
Entire Row: [4 5 6]
Entire Column: [2 5 8]


## Sorting


In [ ]:
unsorted = np.array([2,6,4,7,8,9,3,1])
print("Sorted array",np.sort(unsorted))

unsorted_2d = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array",np.sort(unsorted_2d,axis=0))

Sorted array [1 2 3 4 6 7 8 9]
Sorted 2D array [[1 1]
 [2 2]
 [3 3]]


## Filtering

In [20]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = num[num % 2 ==0]
print("Even Numbers:",even_num)

odd_num = num[num % 2 !=0]
print("Odd Numbers:",odd_num)

Even Numbers: [ 2  4  6  8 10]
Odd Numbers: [1 3 5 7 9]


## filter with Mask

In [22]:
mask = num > 5
print("Numbers greater than 5:",num[mask])

Numbers greater than 5: [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [27]:
indices = [0,2,4]
print(num[indices])

where_result = np.where(num > 5)
print("Indices of numbers greater than 5:",num[where_result])

[1 3 5]
Indices of numbers greater than 5: [ 6  7  8  9 10]


In [30]:
condition_arr = np.where(num > 5,num * 4,num) # if (num > 5) then num *2 else num)
print(condition_arr)

[ 1  2  3  4  5 24 28 32 36 40]


## Adding and Removing Data

In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = arr1 + arr2
print("Combined array:",combined)
concatenated = np.concatenate((arr1,arr2))
print("Concatenated array:",concatenated)

Combined array: [5 7 9]
Concatenated array: [1 2 3 4 5 6]


## Array Compatibility

In [35]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatability check :", a.shape == b.shape == c.shape)

Compatability check : True


In [8]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_row = np.vstack((original,new_row))
print("Vertical Stack:\n",with_row)

new_col = np.array([[7,9],[8,6]])
with_col = np.hstack((original,new_col))
print("Horizontal Stack:\n",with_col)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]
Horizontal Stack:
 [[1 2 7 9]
 [3 4 8 6]]


In [9]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion:",deleted)

Array after deletion: [1 2 4 5]
